env:
  commonjs: true
  node: true
  es2020: true
extends:
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  semi: 0
